#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
package_update: true
package_upgrade: true
packages:
  - python3-pip
  - pipx
  - git
  - python3-venv
write_files:
  - path: /home/ubuntu/.profile
    content: |
       export PATH=$PATH:/home/ubuntu/.local/bin
    append: true
runcmd:
  - chown -R ubuntu:ubuntu /home/ubuntu
